# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_avtorizwindow(object):
    def setupUi(self, avtorizwindow):
        avtorizwindow.setObjectName("avtorizwindow")
        avtorizwindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(avtorizwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(300, 10, 241, 70))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(320, 110, 161, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(320, 170, 161, 41))
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 220, 121, 31))
        self.pushButton.setObjectName("pushButton")
        avtorizwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(avtorizwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        avtorizwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(avtorizwindow)
        self.statusbar.setObjectName("statusbar")
        avtorizwindow.setStatusBar(self.statusbar)

        self.retranslateUi(avtorizwindow)
        QtCore.QMetaObject.connectSlotsByName(avtorizwindow)

    def retranslateUi(self, avtorizwindow):
        _translate = QtCore.QCoreApplication.translate
        avtorizwindow.setWindowTitle(_translate("avtorizwindow", "MainWindow"))
        self.textEdit.setHtml(_translate("avtorizwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Open Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">Авторизация</span></p></body></html>"))
        self.textEdit_2.setPlaceholderText(_translate("avtorizwindow", "Введите логин"))
        self.textEdit_3.setPlaceholderText(_translate("avtorizwindow", "Введите пароль"))
        self.pushButton.setText(_translate("avtorizwindow", "Войти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    avtorizwindow = QtWidgets.QMainWindow()
    ui = Ui_avtorizwindow()
    ui.setupUi(avtorizwindow)
    avtorizwindow.show()
    sys.exit(app.exec_())
