# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panel_povar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Panel_povar(object):
    def __init__(self):
        self.textBrowser = None

    def setupUi(self, Panel_povar):
        Panel_povar.setObjectName("Panel_povar")
        Panel_povar.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Panel_povar)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(190, 10, 321, 70))
        self.textEdit.setObjectName("textEdit")
        self.number_zakaz = QtWidgets.QTextEdit(self.centralwidget)
        self.number_zakaz.setGeometry(QtCore.QRect(20, 130, 211, 41))
        self.number_zakaz.setObjectName("number_zakaz")
        self.number_zakaz_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.number_zakaz_2.setGeometry(QtCore.QRect(20, 180, 211, 41))
        self.number_zakaz_2.setObjectName("number_zakaz_2")
        self.number_zakaz_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.number_zakaz_3.setGeometry(QtCore.QRect(20, 230, 211, 41))
        self.number_zakaz_3.setObjectName("number_zakaz_3")
        self.number_zakaz_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.number_zakaz_4.setGeometry(QtCore.QRect(20, 280, 211, 41))
        self.number_zakaz_4.setObjectName("number_zakaz_4")
        self.number_zakaz_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.number_zakaz_5.setGeometry(QtCore.QRect(20, 330, 211, 41))
        self.number_zakaz_5.setObjectName("number_zakaz_5")
        self.number_zakaz_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.number_zakaz_6.setGeometry(QtCore.QRect(20, 380, 211, 41))
        self.number_zakaz_6.setObjectName("number_zakaz_6")
        self.foot_zakaz_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.foot_zakaz_4.setGeometry(QtCore.QRect(270, 280, 211, 41))
        self.foot_zakaz_4.setObjectName("foot_zakaz_4")
        self.foot_zakaz_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.foot_zakaz_6.setGeometry(QtCore.QRect(270, 380, 211, 41))
        self.foot_zakaz_6.setObjectName("foot_zakaz_6")
        self.foot_zakaz = QtWidgets.QTextEdit(self.centralwidget)
        self.foot_zakaz.setGeometry(QtCore.QRect(270, 130, 211, 41))
        self.foot_zakaz.setObjectName("foot_zakaz")
        self.foot_zakaz_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.foot_zakaz_3.setGeometry(QtCore.QRect(270, 230, 211, 41))
        self.foot_zakaz_3.setObjectName("foot_zakaz_3")
        self.foot_zakaz_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.foot_zakaz_2.setGeometry(QtCore.QRect(270, 180, 211, 41))
        self.foot_zakaz_2.setObjectName("foot_zakaz_2")
        self.foot_zakaz_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.foot_zakaz_5.setGeometry(QtCore.QRect(270, 330, 211, 41))
        self.foot_zakaz_5.setObjectName("foot_zakaz_5")
        self.work = QtWidgets.QPushButton(self.centralwidget)
        self.work.setGeometry(QtCore.QRect(510, 140, 80, 26))
        self.work.setObjectName("work")
        self.comlete = QtWidgets.QPushButton(self.centralwidget)
        self.comlete.setGeometry(QtCore.QRect(600, 140, 80, 26))
        self.comlete.setObjectName("comlete")
        self.work_2 = QtWidgets.QPushButton(self.centralwidget)
        self.work_2.setGeometry(QtCore.QRect(510, 190, 80, 26))
        self.work_2.setObjectName("work_2")
        self.complete = QtWidgets.QPushButton(self.centralwidget)
        self.complete.setGeometry(QtCore.QRect(600, 190, 80, 26))
        self.complete.setObjectName("complete")
        self.work_3 = QtWidgets.QPushButton(self.centralwidget)
        self.work_3.setGeometry(QtCore.QRect(510, 240, 80, 26))
        self.work_3.setObjectName("work_3")
        self.complete_2 = QtWidgets.QPushButton(self.centralwidget)
        self.complete_2.setGeometry(QtCore.QRect(600, 240, 80, 26))
        self.complete_2.setObjectName("complete_2")
        self.work_4 = QtWidgets.QPushButton(self.centralwidget)
        self.work_4.setGeometry(QtCore.QRect(510, 290, 80, 26))
        self.work_4.setObjectName("work_4")
        self.complete_3 = QtWidgets.QPushButton(self.centralwidget)
        self.complete_3.setGeometry(QtCore.QRect(600, 290, 80, 26))
        self.complete_3.setObjectName("complete_3")
        self.work_5 = QtWidgets.QPushButton(self.centralwidget)
        self.work_5.setGeometry(QtCore.QRect(510, 340, 80, 26))
        self.work_5.setObjectName("work_5")
        self.complete_4 = QtWidgets.QPushButton(self.centralwidget)
        self.complete_4.setGeometry(QtCore.QRect(600, 340, 80, 26))
        self.complete_4.setObjectName("complete_4")
        self.work_6 = QtWidgets.QPushButton(self.centralwidget)
        self.work_6.setGeometry(QtCore.QRect(510, 390, 80, 26))
        self.work_6.setObjectName("work_6")
        self.complete_5 = QtWidgets.QPushButton(self.centralwidget)
        self.complete_5.setGeometry(QtCore.QRect(600, 390, 80, 26))
        self.complete_5.setObjectName("complete_5")
        Panel_povar.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Panel_povar)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        Panel_povar.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Panel_povar)
        self.statusbar.setObjectName("statusbar")
        Panel_povar.setStatusBar(self.statusbar)

        self.retranslateUi(Panel_povar)
        QtCore.QMetaObject.connectSlotsByName(Panel_povar)

    def retranslateUi(self, Panel_povar):
        _translate = QtCore.QCoreApplication.translate
        Panel_povar.setWindowTitle(_translate("Panel_povar", "MainWindow"))
        self.textBrowser.setHtml(_translate("Panel_povar", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Open Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">Панель повара</span></p></body></html>"))
        self.work.setText(_translate("Panel_povar", "В работе"))
        self.comlete.setText(_translate("Panel_povar", "Готов"))
        self.work_2.setText(_translate("Panel_povar", "В работе"))
        self.complete.setText(_translate("Panel_povar", "Готов"))
        self.work_3.setText(_translate("Panel_povar", "В работе"))
        self.complete_2.setText(_translate("Panel_povar", "Готов"))
        self.work_4.setText(_translate("Panel_povar", "В работе"))
        self.complete_3.setText(_translate("Panel_povar", "Готов"))
        self.work_5.setText(_translate("Panel_povar", "В работе"))
        self.complete_4.setText(_translate("Panel_povar", "Готов"))
        self.work_6.setText(_translate("Panel_povar", "В работе"))
        self.complete_5.setText(_translate("Panel_povar", "Готов"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Panel_povar = QtWidgets.QMainWindow()
    ui = Ui_Panel_povar()
    ui.setupUi(Panel_povar)
    Panel_povar.show()
    sys.exit(app.exec_())
